name: Auto update

on:
  schedule:
    - cron:  '0 5,13,21 * * *'

  workflow_dispatch:

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Requirements
      run: |
        pip install -r ./utils/requirements
    - name: SubMerge
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
        python ./utils/sub_merge.py
    - name: GitMerge
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add ./merge
        git add v2ray
        git add clash.yaml
        git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') "
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: master
    - name: GitCommit
      run: |                 
        git pull origin master
        git add list.json
        (git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') ") || true
    - name: GitPush
      uses:  ad-m/github-push-action@master
      with:
        branch: master
